version: '3'
services:
  db:
    image: mysql:8
    container_name: local-mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cms-nest
    volumes:
      - H:/Docker/playground/db:/var/lib/mysql
